name: Publish CUI Subsite website ###### <<<<<<<<<<<<<<<<<< CHANGE TO APPROPRIATE NAME

on:
  # Runs on pushes and merged pull requests targeting the default branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push to conversationaluserinterfaces.org repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '.'
          destination-github-username: 'acm-cui'
          destination-repository-name: 'conversationaluserinterfaces.org'
          user-email: 'cuitechchair@gmail.com'
          user-name: 'cuibot'
          target-branch: 'master' # This will change in the future to 'main' or equivalent
          target-directory: 'mysubsitehere' ###### <<<<<<<<<<<<<<<<<< ENSURE YOU CHANGE THIS!!!

